apiVersion: v1
kind: Service
metadata:
  name: airlines
  labels:
    app: airlines
spec:
  ports:
    - port: 9080
      targetPort: 9080
      nodePort: 30080
      name: airlines
    - port: 9443
      targetPort: 9443
      nodePort: 30443
      name: admin
  selector:
    app: airlines
    tier: api
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: airlines
  labels:
    app: airlines
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: airlines
        tier: api
    spec:
      containers:
      - image: registry.ng.bluemix.net/tommy_chaoping/airlines
        name: airlines
        ports:
        - containerPort: 9080
          name: airlines
        - containerPort: 9443
          name: admin