apiVersion: v1
kind: Service
metadata:
  name: apiconnect
  labels:
    app: apiconnect
spec:
  ports:
    - port: 9085
      targetPort: 9085
      nodePort: 30281
      name: apiconnect
    - port: 9448
      targetPort: 9448
      nodePort: 30282
      name: admin
  selector:
    app: apiconnect
    tier: api
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apiconnect
  labels:
    app: apiconnect
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apiconnect
        tier: api
    spec:
      containers:
      - image: registry.ng.bluemix.net/dfplayer/api-connect
        name: apiconnect
        ports:
        - containerPort: 9085
          name: apiconnect
        - containerPort: 9448
          name: admin
