apiVersion: v1
kind: Service
metadata:
  name: couchdb
  labels:
    app: airlines
spec:
  ports:
    - port: 5984
      protocol: TCP
      targetPort: 5984
  selector:
    app: airlines
    tier: couchdb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: couchdb
  labels:
    app: airlines
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: airlines
        tier: couchdb
    spec:
      containers:
      - image: couchdb:latest
        name: couchdb
        ports:
        - containerPort: 5984
          name: couchdb